apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - name: http #9000번 포트 이름
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: grpc #50051번 포트 이름
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer

---
#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
